app:
  # app locale
  locale: et
  dbName: geop
  dbVersion: 1
  layerManager: true
  searchEnabled: true
  locateEnabled: true
  mouseCoordinates: true
  settings: true
  tooltip: true
  featureInfo: true
  scaleLine: true
  streetView: true
  measureTool: true
  fullScreen: true
  screenLock: true
  mousePosition: true
  geoLocation: true
  shareState: true
  # keep only features on trip
  shareOnlyTripFeatures: true
  # active tab on sidebar
  settingsTabOpen: 'settings-tab'
  # collect all console debug, info and error into downloadable file
  debug: false
  debugFile: 'geop_debug.log'
  nominatimCountries: ee
  routing:
    # provider key or null
    provider: openrouteservice
    # driving, hiking, ''
    profile: driving
map:
  el: '#map'
  center:
    - 25.5
    - 58.5
  zoom: 7
  rotation: 0
  extent:
    - 21
    - 57
    - 29
    - 60
  projection: 'EPSG:3857'
  defaultDataProjection: 'EPSG:4326'
  baseLayer: osm
  minZoom: 0
  maxZoom: 20
  clustered: false
api:
  ideditor: 'https://www.openstreetmap.org/edit?editor=id#background=custom:http://tiles.maaamet.ee/tm/tms/1.0.0/foto@GMC/{z}/{x}/{-y}.png&map='
  nominatim: 'https://nominatim.openstreetmap.org'
  jsonstore: 'https://projekt-gp.ee/api/v1/bookmark'
  qrcode: 'http://api.qrserver.com/v1/create-qr-code/?size=150x150&data='
  osrm:
    directions: 'https://router.project-osrm.org/route/v1/'
  openrouteservice:
    key: '5b3ce3597851110001cf6248b99b83882966492086eee3c4a0522e9c'
    directions: 'https://api.openrouteservice.org/v2/directions/'
    optimize: 'https://api.openrouteservice.org/optimization/'
  google:
    streetview: 'https://www.google.com/maps/@?api=1&map_action=pano&viewpoint='
    directions: 'https://www.google.com/maps/dir/?api=1&destination='
  wmsexamples:
    Kataster (WMS): 'http://kaart.maaamet.ee/wms/alus?layers=TOPOYKSUS_6569,TOPOYKSUS_7793&SRS=EPSG:3301&title=Kataster'
    Looduskaitse (WMS): 'https://gsavalik.envir.ee/geoserver/eelis/ows?layers=kr_kaitseala,kr_hoiuala,kr_hooldatav_skv,kr_looduslik_skv,kr_reservaat,kr_vep,plk,kr_kohalik_objekt_pv,kr_yksikobjekti_kaitsetsoon,kr_kohalik_objekt,kr_yksikobjektid&SRS=EPSG:3301&opacity=0.9&title=Looduskaitse'
    Pärandkultuur (WMS): 'https://gsavalik.envir.ee/geoserver/eelis/ows?layers=pk_objekt_metsas&SRS=EPSG:3301&title=Pärandkultuur'
    LV foto (WMS): 'https://wmsbm3.kartes.lv/BMdMiAsVp/wgs/orto/?title=LV orto&layers=0&srs=EPSG:3857'
    LV kaart (WMS): 'https://wmsbm3.kartes.lv/BMdMiAsVp/wgs/15/?title=LV&layers=0&srs=EPSG:3857'
    Soome kaart (WMTS): 'https://mapservices-a.navici.com/basemaps/gwc/service/wmts?apikey=gdqWSTM10Le9XVAX8B6vFKxnpZAmTx5x&title=Soome kaart&layer=basemaps:rk&srs=EPSG:3067&matrixSet=ETRS-TM35FIN&matrixTemplate=ETRS-TM35FIN:{z}&scaleDenominator=2.925714285714286E7&topLeftCorner=-2097152,9437184&matrixWidth=3&matrixHeight=2&format=image/png8'
    Soome foto (WMTS): 'https://www.retkikartta.fi/wmts/30c616a00f157e7357721900e8b0415c/?srs=EPSG:3067&title=Soome foto&format=image/jpeg&layer=ortokuva&matrixSet=ETRS-TM35FIN&scaleDenominator=29257142.85714286&matrixWidth=1&matrixHeight=1&topLeftCorner=-548576,8388608'
